- name: site config backup job
  hosts: "{{ platform }}"
  become: true
  tasks:
    - name: Set Date variable
      shell: date +%Y%m%d
      register: current_date_result

    - name: Set Hostname variable
      shell: hostname
      register: hostname_result

    - name: Take Backup
      shell: >
        find -L /netappwebsites -maxdepth 4 -type f \( -name ".env" -o -name ".htaccess" -o -name "wp-config.php" \) -exec tar -cvhf /backup/{{ dir }}/site_config_backup/{{ current_date_result.stdout }}_{{ hostname_result.stdout }}_siteconfig.tar {} +
