---
- name: Backup System Configuration
  become: true
  hosts: "{{ platform }}"
  vars_files:
    - var_files/{{ server }}_dir.yml
 
  tasks:
  - name: PHP Configuration Backup
    archive:
      path: "/etc/opt/remi/*/php-fpm.d/*.conf"
      dest: "/backup/{{ dir }}/php_conf_{{ansible_date_time.date}}.tgz"

  - name: Httpd Configuration Backup
    archive:
      path: "/etc/httpd/sites-available"
      dest: "/backup/{{ dir }}/httpd_conf_{{ansible_date_time.date}}.tgz"

  - name: Auth Available Backup
    archive:
      path: "/etc/httpd/auth-available"
      dest: "/backup/{{ dir }}/auth-available_{{ansible_date_time.date}}.tgz"

  - name: Auth File Backup
    archive:
      path: "/etc/httpd/auth-files"
      dest: "/backup/{{ dir }}/auth-files_{{ansible_date_time.date}}.tgz"

  - name: HTTP rules Backup
    archive:
      path: "/etc/httpd/sites-configuration"
      dest: "/backup/{{ dir }}/sites-configuration_{{ansible_date_time.date}}.tgz"

  - name: Websites Backup
    archive:
      path: "/netappwebsites"
      dest: "/backup/{{ dir }}/web_data_{{ansible_date_time.date}}.tgz"
      tar_options: "--exclude='/netappwebsites/*/logs' --exclude='/netappwebsites/gitlab_job' --exclude='/netappwebsites/lost+found'"
