- hosts: localhost
  vars_files:
    - var_files/{{ platform }}_db.yml
  tasks:
  - name: Check if site exists in index file
    shell: grep {{ site_url }} /home/c4eadmin/{{ platform }}_php_site_index.txt | awk '{ print $6 }'
    register: db_name

  - name: Site not exists 
    debug:
     msg: "Database for {{ site_url }} doesn't exists. Hence skipping the below tasks"
    when: db_name.stdout == "" 
  - name: Site exists   
    debug: 
     msg: "Database name for {{ site_url }} is: {{ db_name.stdout }}"
    when: db_name.stdout != ""
 
  - name: Create Directories if the site exists
    file:
      path: /backup/{{ platform }}
      state: directory
      mode: '0700'
    when: db_name.stdout != "" 
  

  - name: Take Backup
    shell: mysqldump --force --opt --skip-lock-tables -h {{ db_host }} -u {{ db_user }}  -p"{{ db_pass }}" --databases {{ db_name.stdout }}| gzip > /backup/{{ platform }}/{{ db_name.stdout }}_{{ ansible_date_time.date }}.sql.gz
    when: db_name.stdout != ""
