---
- name: Server Hardening
  become: true
  hosts: all
  tasks:
  - name: Create LVM on datadisk
    ansible.builtin.script: templates/datadisk_lvm.sh

  - name: Running Server Hardening
    ansible.builtin.script: templates/server_hardening.sh
  
  - name: Rebooting server to apply changes
    ansible.builtin.reboot:
