---
- name: List site
  become: true
  hosts: "{{ env }}_webservers"

  tasks:
  - name: get all sites on server
    ansible.builtin.command: a2query -s
    register: site_list

  - name: Display all sites on server
    ansible.builtin.debug:
      msg: "{{ site_list.stdout_lines }}"